name: cartserviceci

on: 
  workflow_dispatch:


# on:
#   push:
#     branches:
#       - main  # Set the branch you want to trigger the workflow on
#     paths-ignore:
#       - 'helm/**'
#       - 'k8s/**'
#       - '.github/workflows/**'
#       - 'README.md'
#       - 'src/adservice/**'
#       - 'src/paymentservice/**'
#       - 'src/checkoutservice/**'
#       - 'src/frontend/**'
#       - 'src/emailservice/**'
#       - 'src/loadgenerator/**'
#       - 'src/currencyservice/**'
#       - 'src/productcatalogservice/**'
#       - 'src/recommendationservice/**'
#       - 'src/shippingservice/**'
#       - 'src/shoppingassistantservice/**'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up .NET Core
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: '5.x'  # Update with your desired .NET version

      # - name: Restore dependencies
      #   run: dotnet restore ./src/cartservice/src

      # - name: Build
      #   run: dotnet build --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the current directory as the build context
          file: ./src/cartservice/src/Dockerfile  # Path to your Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cart-service:${{github.run_id}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # Optionally, deploy your application using Kubernetes or other means

      - name: Cleanup
        run: docker system prune -af
    
  update-newtag-in-helm-chart:
    runs-on: self-hosted

    needs: build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/cartservicetag: .*/cartservicetag: "${{github.run_id}}"/' helm/cartservice-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "nsnnln@gmail.com"
        git config --global user.name "abhi-nsn0304"
        git add helm/cartservice-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
