name: paymentserviceci


on: 
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - main  # Set the branch you want to trigger the workflow on
#     paths-ignore:
#       - 'helm/**'
#       - 'k8s/**'
#       - '.github/workflows/**'
#       - 'README.md'
#       - 'src/adservice/**'
#       - 'src/cartservice/**'
#       - 'src/checkoutservice/**'
#       - 'src/frontend/**'
#       - 'src/emailservice/**'
#       - 'src/loadgenerator/**'
#       - 'src/currencyservice/**'
#       - 'src/productcatalogservice/**'
#       - 'src/recommendationservice/**'
#       - 'src/shippingservice/**'
#       - 'src/shoppingassistantservice/**'

jobs:
  # sonarqube-analysis:
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     # - name: Set up SonarQube Scanner
  #     #   uses: sonarsource/sonarcloud-github-action@v1
  #     #   with:
  #     #     token: ${{ secrets.SONAR_TOKEN }}

  #     - name: SonarQube Scan
  #       run: |
  #         sonar-scanner \
  #           -Dsonar.projectKey=PaymentService \
  #           -Dsonar.sources=./src/paymentservice \
  #           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
  #           -Dsonar.login=${{ secrets.SONAR_PAYMENTSERVICE_TOKEN }}
  # Owasp-dependency-check:
  #   runs-on: self-hosted
  #   needs: sonarqube-analysis

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Run OWASP Dependency-Check
  #       run: |
  #         dependency-check.sh \
  #           --project PaymentService \
  #           --out ./src/paymentservice/dependency-check-report \
  #           --scan ./src/paymentservice \
  #           --format "ALL"

  #     - name: Upload Dependency-Check Report
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: dependency-check-report
  #         path: ./src/paymentservice/dependency-check-report

  build-and-push:
    runs-on: ubuntu-latest
    # needs: Owasp-dependency-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the current directory as the build context
          file: ./src/paymentservice/Dockerfile  # Path to your Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:${{github.run_id}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  # trivy-scan:
  #   runs-on: self-hosted
  #   needs: build-and-push

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Scan Docker image with Trivy
  #       run: |
  #         trivy image --no-progress --format table ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:${{ github.run_id }}  > ./trivy-scan-results.txt

  #     - name: Upload Trivy scan results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: trivy-scan-results
  #         path: ./trivy-scan-results.txt

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    # needs: trivy-scan
    needs: build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/paymentservicetag: .*/paymentservicetag: "${{github.run_id}}"/' helm/paymentservice-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "nsnnln@gmail.com"
        git config --global user.name "abhi-nsn0304"
        git add helm/paymentservice-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push